version: '3.8'

services:
  api:
    image: python:3.11-alpine
    ports:
      - "8080:8000"
    volumes:
      - ./simple-api:/app
    working_dir: /app
    command: >
      sh -c "pip install flask &&
              python app.py"
    restart: unless-stopped 
