echo "🐳 Добро пожаловать в DESQEMU Alpine Linux!"
echo "📦 Podman версия: \$(podman --version)"
echo "🖥️  QEMU версия: \$(qemu-system-x86_64 --version | head -1)"
echo "🌐 Chromium версия: \$(chromium --version)"
echo "🚀 Готов к запуску контейнеров и веб-приложений!"
echo ""
echo "Полезные команды:"
echo "  podman run hello-world                    - тест Podman"
echo "  podman ps                                 - список контейнеров"
echo "  chromium --headless --remote-debugging-port=9222 - headless Chromium"
echo "  startx                                    - запуск X11 окружения"
echo "  docker-compose up -d                      - запуск docker-compose"
echo "" 
