name: Создание Alpine дистрибутива с Podman

# When to run this workflow / Когда запускать этот workflow
on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/alpine-podman-distribution.yml'
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/alpine-podman-distribution.yml'
  workflow_dispatch:  # Manual trigger / Ручной запуск
    inputs:
      alpine_version:
        description: 'Версия Alpine Linux'
        required: false
        default: '3.19'
        type: string
      architecture:
        description: 'Архитектура'
        required: false
        default: 'x86_64'
        type: choice
        options:
          - 'x86_64'
          - 'aarch64'
          - 'arm64'
          - 'amd64'

env:
  ALPINE_VERSION: ${{ github.event.inputs.alpine_version || '3.19' }}

jobs:
  create-qemu-portable-archive:
    name: Создание портативного архива с QEMU и микровм
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [x86_64, aarch64, arm64]
        include:
          - architecture: x86_64
            qemu_arch: x86_64
            host_arch: linux-x64
          - architecture: aarch64  
            qemu_arch: aarch64
            host_arch: linux-arm64
          - architecture: arm64
            qemu_arch: aarch64
            host_arch: linux-arm64
    permissions:
      contents: read
      packages: write
    steps:
      - name: 📥 Получение кода репозитория | Get repository code
        uses: actions/checkout@v4

      - name: 🔧 Установка зависимостей | Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl xz-utils

      - name: 🚀 Создание портативного архива | Create portable archive
        run: |
          echo "🚀 Запускаем сборку портативного архива для ${{ matrix.architecture }}..."
          chmod +x scripts/build-portable.sh
          scripts/build-portable.sh ${{ matrix.architecture }}

      - name: 🛠️ Создание универсального установщика | Create universal installer
        run: |
          echo "🛠️ Создаем универсальный установщик..."
          chmod +x scripts/create-universal-installer.sh
          scripts/create-universal-installer.sh

      - name: ⬆️ Портативный архив → GitHub Artifacts | Upload portable archive to GitHub Artifacts  
        uses: actions/upload-artifact@v4
        with:
          name: desqemu-portable-microvm-${{ matrix.architecture }}
          path: |
            desqemu-portable-microvm-${{ matrix.architecture }}.tar.gz
            install-desqemu-portable-${{ matrix.architecture }}.sh
            install-desqemu-portable.sh
          retention-days: 30

  create-alpine-distribution:
    name: Создание Alpine дистрибутива с Podman
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [x86_64, aarch64, arm64, amd64]
        include:
          - architecture: x86_64
            platform: linux/amd64
          - architecture: aarch64
            platform: linux/arm64
          - architecture: arm64
            platform: linux/arm64
          - architecture: amd64
            platform: linux/amd64
    permissions:
      contents: read
      packages: write
    steps:
      - name: 📥 Получение кода репозитория | Get repository code
        uses: actions/checkout@v4

      - name: 🐳 Настройка Docker Buildx | Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔨 Подготовка Dockerfile для CI/CD | Prepare Dockerfile for CI/CD
        run: |
          echo "🐳 Подготавливаем Dockerfile для CI/CD..."

          # Update Dockerfile with correct Alpine version
          # Обновляем Dockerfile с правильной версией Alpine
          sed -i "s/FROM alpine:3.19/FROM alpine:${{ env.ALPINE_VERSION }}/" Dockerfile

          # Update labels with correct version
          # Обновляем метки с правильной версией
          sed -i "s/version=\"3.19\"/version=\"${{ env.ALPINE_VERSION }}\"/" Dockerfile

      - name: 🏗️ Сборка Alpine образа | Build Alpine image
        run: |
          echo "🔨 Собираем кастомный Alpine образ для ${{ matrix.platform }}..."
          docker buildx build --platform ${{ matrix.platform }} --target final-image -t desqemu-alpine:latest .

      - name: 🚀 Пуш в GitHub Container Registry | Push to GitHub Container Registry
        run: |
          echo "🚀 Пушим образ в GitHub Container Registry..."

          # Login to GitHub Container Registry using GITHUB_TOKEN
          # Логинимся в GitHub Container Registry используя GITHUB_TOKEN
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          # Tag image for GitHub Container Registry
          # Обвешиваем тегом образ для GitHub Container Registry
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/desqemu-alpine"
          
          # Build and push with platform-specific tags
          # Собираем и пушим с платформо-специфичными тегами
          docker buildx build --platform ${{ matrix.platform }} --target final-image \
            -t "$IMAGE_NAME:latest" \
            -t "$IMAGE_NAME:${{ env.ALPINE_VERSION }}" \
            -t "$IMAGE_NAME:${{ env.ALPINE_VERSION }}-${{ matrix.architecture }}" \
            --push .

          echo "✅ Образ опубликован в ghcr.io/${{ github.repository_owner }}/desqemu-alpine"
          echo "📥 Для скачивания: docker pull ghcr.io/${{ github.repository_owner }}/desqemu-alpine:latest"

      - name: 📦 Экспорт в rootfs для chroot | Export to rootfs for chroot
        run: |
          echo "📦 Экспортируем образ в rootfs..."

          # Create container and export its filesystem to a temporary directory
          # Создаем контейнер и экспортируем его файловую систему во временную директорию
          mkdir -p rootfs-temp
          CONTAINER_ID=$(docker create desqemu-alpine:latest)
          docker export $CONTAINER_ID | tar -C rootfs-temp -x
          docker rm $CONTAINER_ID

          # Create rootfs archive (exclude virtual filesystems)
          # Создаем архив rootfs (исключаем виртуальные файловые системы)
          cd rootfs-temp
          tar -czf "../desqemu-alpine-rootfs-${{ env.ALPINE_VERSION }}-${{ matrix.architecture }}.tar.gz" \
            --exclude='./dev/*' \
            --exclude='./proc/*' \
            --exclude='./sys/*' \
            --exclude='./tmp/*' \
            --exclude='./run/*' \
            --exclude='./mnt/*' \
            --exclude='./media/*' \
            --exclude='./.dockerenv' \
            .
          cd ..

          # Clean up temporary files / Очищаем временные файлы
          rm -rf rootfs-temp

          echo "✅ Rootfs создан: $(du -h desqemu-alpine-rootfs-*.tar.gz | cut -f1)"

      - name: 💾 Сохранение Docker образа | Save Docker image
        run: |
          echo "🐳 Сохраняем Docker образ..."
          docker save desqemu-alpine:latest | gzip > desqemu-alpine-docker-${{ env.ALPINE_VERSION }}-${{ matrix.architecture }}.tar.gz
          echo "✅ Docker образ сохранен: $(du -h desqemu-alpine-docker-*.tar.gz | cut -f1)"

      - name: 📚 Создание документации | Create documentation
        run: |
          echo "📚 Создаем документацию и скрипты..."
          chmod +x scripts/create-all-docs.sh
          scripts/create-all-docs.sh ${{ env.ALPINE_VERSION }} ${{ matrix.architecture }} ${{ github.repository_owner }}



      - name: ⬆️ Docker образ → GitHub Artifacts | Upload Docker image to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desqemu-alpine-docker-${{ env.ALPINE_VERSION }}-${{ matrix.architecture }}
          path: |
            desqemu-alpine-docker-${{ env.ALPINE_VERSION }}-${{ matrix.architecture }}.tar.gz
            quick-start-docker.sh
            quick-start-with-compose.sh
            DESQEMU-Alpine-README.md
          retention-days: 30

      - name: ⬆️ Rootfs → GitHub Artifacts | Upload rootfs to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desqemu-alpine-rootfs-${{ env.ALPINE_VERSION }}-${{ matrix.architecture }}
          path: |
            desqemu-alpine-rootfs-${{ env.ALPINE_VERSION }}-${{ matrix.architecture }}.tar.gz
            quick-start-rootfs.sh
            quick-start-with-compose.sh
            DESQEMU-Alpine-README.md
          retention-days: 30

      - name: ⬆️ Release notes → Artifacts | Upload release notes to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: release-notes.md
          retention-days: 7

      - name: 🏷️ Создание GitHub Release | Create GitHub Release (tags only)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "DESQEMU Alpine Linux ${{ env.ALPINE_VERSION }} с Podman"
          body_path: release-notes.md
          files: |
            desqemu-alpine-docker-${{ env.ALPINE_VERSION }}-${{ matrix.architecture }}.tar.gz
            desqemu-alpine-rootfs-${{ env.ALPINE_VERSION }}-${{ matrix.architecture }}.tar.gz
            quick-start-docker.sh
            quick-start-rootfs.sh
            quick-start-with-compose.sh
            DESQEMU-Alpine-README.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-portable-release:
    name: Создание релиза портативных архивов
    runs-on: ubuntu-latest
    needs: [create-qemu-portable-archive]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: 📥 Получение кода репозитория | Get repository code
        uses: actions/checkout@v4

      - name: 📦 Скачивание всех портативных архивов | Download all portable archives
        uses: actions/download-artifact@v4
        with:
          pattern: desqemu-portable-microvm-*
          merge-multiple: true

      - name: 📝 Создание release notes для портативных архивов | Create release notes for portable archives
        run: |
          echo "📝 Создаем release notes для портативных архивов..."
          chmod +x scripts/create-portable-release-notes.sh
          scripts/create-portable-release-notes.sh "${{ github.repository }}" "${{ github.ref_name }}" "${{ github.repository_owner }}" "${{ github.server_url }}"

      - name: 🏷️ Создание GitHub Release для портативных архивов | Create GitHub Release for portable archives
        uses: softprops/action-gh-release@v1
        with:
          name: "🚀 DESQEMU Portable MicroVM ${{ github.ref_name }}"
          body_path: portable-release-notes.md
          files: |
            desqemu-portable-microvm-*.tar.gz
            install-desqemu-portable-*.sh
            install-desqemu-portable.sh
          tag_name: "${{ github.ref_name }}-portable"
          draft: false
          prerelease: false
          make_latest: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
