# ============================================================================
# GitHub Actions Workflow для создания DESQEMU дистрибутивов
# ============================================================================
#
# 🏗️ Этот workflow создает ТРИ независимых типа артефактов:
#
# 1️⃣ ПОРТАТИВНЫЕ АРХИВЫ (create-qemu-portable-archive):
#    📦 Самодостаточные архивы с QEMU бинарниками
#    🔧 Установочные скрипты для быстрого развертывания
#    🚀 Используются для создания микро-ВМ без Docker
#
# 2️⃣ ALPINE ДИСТРИБУТИВ (create-alpine-distribution):
#    🐳 Docker образы с Alpine Linux + Podman
#    📁 Rootfs архивы для chroot окружений
#    🔄 Совместимы с различными контейнерными платформами
#
# 3️⃣ ALPINE QCOW2 ОБРАЗЫ (create-alpine-qcow2-images):
#    💿 QCOW2 образы для QEMU виртуальных машин
#    🐧 Готовые к загрузке Alpine Linux ВМ
#    🔧 Создаются с помощью alpine-make-vm-image
#
# ⚡ Джобы выполняются ПАРАЛЛЕЛЬНО для ускорения сборки
# 🔄 Четвертая джоба (create-portable-release) зависит от первой
# ============================================================================

name: Создание Alpine дистрибутива с Podman

# When to run this workflow / Когда запускать этот workflow
on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/alpine-podman-distribution.yml"
  pull_request:
    branches: [master]
    paths:
      - ".github/workflows/alpine-podman-distribution.yml"
  workflow_dispatch: # Manual trigger / Ручной запуск
    inputs:
      alpine_version:
        description: "Версия Alpine Linux"
        required: false
        default: "3.19"
        type: string
      architecture:
        description: "Архитектура"
        required: false
        default: "x86_64"
        type: choice
        options:
          - "x86_64"
          - "aarch64"
          - "arm64"
          - "amd64"

env:
  ALPINE_VERSION: ${{ github.event.inputs.alpine_version || '3.19' }}

jobs:


  build-desktop-app:
    name: 🖥️ Сборка Desktop приложения
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 📥 Получение кода репозитория | Get repository code
        uses: actions/checkout@v4

      - name: 🔧 Установка Node.js | Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: desqemu-desktop/package.json

      - name: 📦 Установка зависимостей | Install dependencies
        run: |
          cd desqemu-desktop
          npm install
          npm install -g @neutralinojs/neu

      - name: 🔨 Сборка Desktop приложения | Build desktop app
        run: |
          cd desqemu-desktop
          neu update
          neu build --release
          
          # Создание архива для распространения
          cd dist
          tar -czf "../../desqemu-desktop-linux-x64.tar.gz" .
          cd ..
          
          echo "✅ Desktop приложение собрано"

      - name: ⬆️ Desktop App → GitHub Artifacts | Upload desktop app to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desqemu-desktop
          path: |
            desqemu-desktop-linux-x64.tar.gz
          retention-days: 30

  create-alpine-distribution:
    name: Создание Alpine дистрибутива (Docker + Rootfs + QCOW2 + Portable)
    runs-on: ubuntu-latest
    needs: [build-desktop-app]
    strategy:
      matrix:
        architecture: [x86_64]
        include:
          - architecture: x86_64
            platform: linux/amd64
    permissions:
      contents: write
      packages: write
    steps:
      - name: 📥 Получение кода репозитория | Get repository code
        uses: actions/checkout@v4

      - name: 🔧 Установка зависимостей | Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl xz-utils qemu-utils fdisk e2fsprogs dosfstools

      - name: 🐳 Настройка Docker Buildx | Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔨 Подготовка Dockerfile для CI/CD | Prepare Dockerfile for CI/CD
        run: |
          echo "🐳 Подготавливаем Dockerfile для CI/CD..."

          # Update Dockerfile with correct Alpine version
          # Обновляем Dockerfile с правильной версией Alpine
          sed -i "s/FROM alpine:3.19/FROM alpine:${{ env.ALPINE_VERSION }}/" Dockerfile

          # Update labels with correct version
          # Обновляем метки с правильной версией
          sed -i "s/version=\"3.19\"/version=\"${{ env.ALPINE_VERSION }}\"/" Dockerfile

      - name: 🏗️ Сборка Alpine образа | Build Alpine image
        run: |
          echo "🔨 Собираем кастомный Alpine образ для ${{ matrix.platform }}..."
          echo "📋 Отладочная информация:"
          echo "   • matrix.architecture: ${{ matrix.architecture }}"
          echo "   • matrix.platform: ${{ matrix.platform }}"
          echo "   • env.ALPINE_VERSION: ${{ env.ALPINE_VERSION }}"
          
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/desqemu-alpine"
          
          # Проверяем, что platform определена
          if [ -z "${{ matrix.platform }}" ]; then
            echo "❌ Ошибка: matrix.platform не определена!"
            exit 1
          fi
          
          docker buildx build --platform ${{ matrix.platform }} --target final-image \
            -t desqemu-alpine:latest \
            -t "$IMAGE_NAME:latest" \
            --load .

          echo "✅ Сборка завершена"
          echo "📋 Проверяем созданные образы:"
          docker images | grep desqemu-alpine

      - name: 🚀 Пуш в GitHub Container Registry | Push to GitHub Container Registry
        run: |
          echo "🚀 Пушим образ в GitHub Container Registry..."

          # Login to GitHub Container Registry using GITHUB_TOKEN
          # Логинимся в GitHub Container Registry используя GITHUB_TOKEN
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          # Tag image for GitHub Container Registry
          # Обвешиваем тегом образ для GitHub Container Registry
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/desqemu-alpine"

          # Build and push with platform-specific tags
          # Собираем и пушим с платформо-специфичными тегами
          docker buildx build --platform ${{ matrix.platform }} --target final-image \
            -t "$IMAGE_NAME:latest" \
            -t "$IMAGE_NAME:${{ env.ALPINE_VERSION }}" \
            -t "$IMAGE_NAME:${{ env.ALPINE_VERSION }}-${{ matrix.architecture }}" \
            --push .

          echo "✅ Образ опубликован в ghcr.io/${{ github.repository_owner }}/desqemu-alpine"
          echo "📥 Для скачивания: docker pull ghcr.io/${{ github.repository_owner }}/desqemu-alpine:latest"

      - name: 📦 Экспорт в rootfs для chroot | Export to rootfs for chroot
        run: |
          echo "📦 Экспортируем образ в rootfs..."

          # Use the locally built image instead of pulling from GHCR
          # Используем локально собранный образ вместо скачивания из GHCR
          IMAGE_NAME="desqemu-alpine:latest"

          # Check if image exists
          # Проверяем существование образа
          if ! docker image inspect "$IMAGE_NAME" >/dev/null 2>&1; then
            echo "❌ Образ $IMAGE_NAME не найден!"
            echo "📋 Доступные образы:"
            docker images
            exit 1
          fi

          echo "✅ Образ $IMAGE_NAME найден"

          # Create container and export its filesystem to a temporary directory
          # Создаем контейнер и экспортируем его файловую систему во временную директорию
          mkdir -p rootfs-temp
          CONTAINER_ID=$(docker create "$IMAGE_NAME")
          docker export $CONTAINER_ID | tar -C rootfs-temp -x
          docker rm $CONTAINER_ID

          # Create rootfs archive (exclude virtual filesystems)
          # Создаем архив rootfs (исключаем виртуальные файловые системы)
          cd rootfs-temp
          tar -czf "../desqemu-alpine-rootfs-${{ env.ALPINE_VERSION }}-${{ matrix.architecture }}.tar.gz" \
            --exclude='./dev/*' \
            --exclude='./proc/*' \
            --exclude='./sys/*' \
            --exclude='./tmp/*' \
            --exclude='./run/*' \
            --exclude='./mnt/*' \
            --exclude='./media/*' \
            --exclude='./.dockerenv' \
            .
          cd ..

          # Clean up temporary files / Очищаем временные файлы
          rm -rf rootfs-temp

          echo "✅ Rootfs создан: $(du -h desqemu-alpine-rootfs-*.tar.gz | cut -f1)"

      - name: 💾 Сохранение Docker образа | Save Docker image
        run: |
          echo "🐳 Сохраняем Docker образ..."
          IMAGE_NAME="desqemu-alpine:latest"

          # Check if image exists
          # Проверяем существование образа
          if ! docker image inspect "$IMAGE_NAME" >/dev/null 2>&1; then
            echo "❌ Образ $IMAGE_NAME не найден!"
            echo "📋 Доступные образы:"
            docker images
            exit 1
          fi

          echo "✅ Образ $IMAGE_NAME найден"
          docker save "$IMAGE_NAME" | gzip > desqemu-alpine-docker-${{ env.ALPINE_VERSION }}-${{ matrix.architecture }}.tar.gz
          echo "✅ Docker образ сохранен: $(du -h desqemu-alpine-docker-*.tar.gz | cut -f1)"

      - name: 📚 Создание документации | Create documentation
        run: |
          echo "📚 Создаем документацию и скрипты..."
          chmod +x scripts/create-all-docs.sh
          scripts/create-all-docs.sh ${{ env.ALPINE_VERSION }} ${{ matrix.architecture }} ${{ github.repository_owner }}

      - name: ⬆️ Docker образ → GitHub Artifacts | Upload Docker image to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desqemu-alpine-docker-${{ env.ALPINE_VERSION }}-${{ matrix.architecture }}
          path: |
            desqemu-alpine-docker-${{ env.ALPINE_VERSION }}-${{ matrix.architecture }}.tar.gz
            quick-start-docker.sh
            quick-start-with-compose.sh
            DESQEMU-Alpine-README.md
          retention-days: 30

      - name: ⬆️ Rootfs → GitHub Artifacts | Upload rootfs to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desqemu-alpine-rootfs-${{ env.ALPINE_VERSION }}-${{ matrix.architecture }}
          path: |
            desqemu-alpine-rootfs-${{ env.ALPINE_VERSION }}-${{ matrix.architecture }}.tar.gz
            quick-start-rootfs.sh
            quick-start-with-compose.sh
            DESQEMU-Alpine-README.md
          retention-days: 30

      - name: 🔧 Загрузка NBD модуля | Load NBD kernel module
        run: sudo modprobe nbd max_part=16

      - name: 🚀 Создание QCOW2 образа | Create QCOW2 image
        run: |
          echo "🚀 Запускаем сборку QCOW2 образа для ${{ matrix.architecture }}..."
          chmod +x scripts/create-alpine-qcow2.sh
          scripts/create-alpine-qcow2.sh ${{ matrix.architecture }} ${{ env.ALPINE_VERSION }}

      - name: ⬆️ QCOW2 образ → GitHub Artifacts | Upload QCOW2 image to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desqemu-alpine-qcow2-${{ matrix.architecture }}
          path: |
            desqemu-alpine-qcow2-${{ matrix.architecture }}.qcow2
            quick-start-qcow2.sh
          retention-days: 30

      - name: 🚀 Создание портативного архива | Create portable archive
        run: |
          echo "🚀 Запускаем сборку портативного архива для ${{ matrix.architecture }}..."
          chmod +x scripts/build-portable.sh
          scripts/build-portable.sh ${{ matrix.architecture }}

      - name: 🛠️ Создание универсального установщика | Create universal installer
        run: |
          echo "🛠️ Создаем универсальный установщик..."
          chmod +x scripts/create-universal-installer.sh
          scripts/create-universal-installer.sh

      - name: ⬆️ Портативный архив → GitHub Artifacts | Upload portable archive to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desqemu-portable-microvm-${{ matrix.architecture }}
          path: |
            desqemu-portable-microvm-${{ matrix.architecture }}.tar.gz
            install-desqemu-portable-${{ matrix.architecture }}.sh
            install-desqemu-portable.sh
          retention-days: 30

      - name: ⬆️ Release notes → Artifacts | Upload release notes to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: release-notes.md
          retention-days: 7

      - name: 📦 Скачивание Desktop App | Download desktop app
        uses: actions/download-artifact@v4
        with:
          name: desqemu-desktop
          path: .


      - name: 📋 Информация о созданных файлах | Information about created files
        run: |
          echo "📋 Созданные файлы:"
          ls -la *.qcow2 *.tar.gz *.sh *.md 2>/dev/null || echo "Файлы не найдены"
          
          echo ""
          echo "📊 Размеры файлов:"
          du -h *.qcow2 *.tar.gz 2>/dev/null || echo "Файлы не найдены"
          
          echo ""
          echo "✅ Все файлы созданы и загружены в GitHub Artifacts"
          echo "📥 Для скачивания: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"



  create-portable-release:
    name: Создание релиза портативных архивов
    runs-on: ubuntu-latest
    needs: [create-alpine-distribution]
    permissions:
      contents: write
    steps:
      - name: 📥 Получение кода репозитория | Get repository code
        uses: actions/checkout@v4

      - name: 📦 Скачивание всех артефактов | Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: |
            desqemu-portable-microvm-*
            desqemu-desktop
          merge-multiple: true

      - name: 📝 Создание release notes для портативных архивов | Create release notes for portable archives
        run: |
          echo "📝 Создаем release notes для портативных архивов..."
          chmod +x scripts/create-portable-release-notes.sh
          scripts/create-portable-release-notes.sh "${{ github.repository }}" "${{ github.ref_name }}" "${{ github.repository_owner }}" "${{ github.server_url }}"

      - name: 🏷️ Создание GitHub Release для портативных архивов | Create GitHub Release for portable archives
        uses: softprops/action-gh-release@v1
        with:
          name: "🚀 DESQEMU Portable MicroVM ${{ github.ref_name }}"
          body_path: portable-release-notes.md
          files: |
            desqemu-portable-microvm-*.tar.gz
            install-desqemu-portable-*.sh
            install-desqemu-portable.sh
            desqemu-desktop-linux-x64.tar.gz
          tag_name: "${{ github.ref_name }}-portable"
          draft: false
          prerelease: false
          make_latest: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
